#theme: jekyll-theme-architect

repository: peterwwillis/devopsyoga-content
url: https://devops.yoga
title: DevOps.yoga
description: 'A DevOps Wiki'

plugins:
    - jekyll-sitemap

encoding: utf-8

# We need to exclude at least the 'rvm' directory, because there are some
# Markdown examples which have bad UTF-8 and kill Jekyll. Also, extra files
# slow down the generation and creates pages we don't want.
# Note: Make sure the * character is in quotes! Yaml is picky.
exclude:
    - .bundle
    - vendor
    - rvm

